// Generated by scripts/generate-observer-cities.mjs — do not edit manually.
// City data lives in data/source/observer-cities.json.

export interface ObserverCity {
  city: string;
  country: string;
  latitude: number;
  longitude: number;
}

export const CUSTOM_LOCATION_ID = "custom";

let cachedCities: ObserverCity[] | null = null;

export function formatObserverCityLabel(city: ObserverCity): string {
  return `${city.city}, ${city.country}`;
}

export function observerCityKey(city: ObserverCity): string {
  return `${city.latitude},${city.longitude}`;
}

export async function loadObserverCities(): Promise<ObserverCity[]> {
  if (cachedCities) {
    return cachedCities;
  }

  const data = await import("../../data/source/observer-cities.json");
  const cities = (data.default ?? data) as ObserverCity[];
  cachedCities = [...cities].sort((a, b) =>
    formatObserverCityLabel(a).localeCompare(formatObserverCityLabel(b)),
  );
  return cachedCities;
}

export function findObserverCity(
  latitude: number,
  longitude: number,
  cities: ObserverCity[],
): ObserverCity | undefined {
  return cities.find(
    (city) => city.latitude === latitude && city.longitude === longitude,
  );
}

export function findObserverCityByKey(
  key: string,
  cities: ObserverCity[],
): ObserverCity | undefined {
  return cities.find((city) => observerCityKey(city) === key);
}
